const coupons = [
  {
    app_url: null,
    coupon_code: 'TIKILAMQUEN625',
    coupon_id: 61084307,
    coupon_type: 'TIKI_COUPON',
    discount_amount: 0,
    expired_at: 1664557199,
    icon_name: '',
    icon_url:
      'https://salt.tikicdn.com/cache/128x128/ts/upload/92/ad/57/0d9a096885400b7b4752b67afdc72898.png',
    label: 'Hoàn 25K Xu',
    long_description:
      'Hoàn 25K Xu cho đơn hàng từ 99K.\nKhông áp dụng cho các sản phẩm trong danh mục Sữa cho bé dưới 24 tháng, Bia và Nước hoa quả lên men, Phiếu quà tặng, Voucher - Dịch vụ, Sản phẩm dịch vụ số, Sim số - Thẻ cảo - Thẻ game, Mã Phiếu Quà Tặng Tiki, Mì Gói, Rượu từ 15%.\nKhông áp dụng cho 1 số nhà bán.\nChỉ áp dụng cho khách hàng mới.\nMỗi khách hàng được sủ dụng tối đa 1 lần.',
    min_amount: 0,
    out_of_stock: false,
    payment: null,
    period: 'HSD: 30/09/22',
    rule_id: 2953346,
    saved: false,
    seller_id: 0,
    seller_name: null,
    short_description: 'Cho đơn hàng từ 99K',
    short_title: 'Hoàn 25K Xu',
    simple_action: 'cart_fixed',
    status: 'active',
    tags: ['KH mới'],
    url: '',
    web_url: null,
  },
  {
    app_url: null,
    coupon_code: 'TIKILAMQUEN650',
    coupon_id: 61084247,
    coupon_type: 'TIKI_COUPON',
    discount_amount: 0,
    expired_at: 1664557199,
    icon_name: '',
    icon_url:
      'https://salt.tikicdn.com/cache/128x128/ts/upload/92/ad/57/0d9a096885400b7b4752b67afdc72898.png',
    label: 'Hoàn 50K Xu',
    long_description:
      'Hoàn 50K Xu cho đơn hàng từ 200K.\nKhông áp dụng cho các sản phẩm trong danh mục Sữa cho bé dưới 24 tháng, Bia và Nước hoa quả lên men, Phiếu quà tặng, Voucher - Dịch vụ, Sản phẩm dịch vụ số, Sim số - Thẻ cảo - Thẻ game, Mã Phiếu Quà Tặng Tiki, Mì Gói, Rượu từ 15%.\nKhông áp dụng cho 1 số nhà bán.\nChỉ áp dụng cho khách hàng mới.\nMỗi khách hàng được sủ dụng tối đa 1 lần.',
    min_amount: 0,
    out_of_stock: false,
    payment: null,
    period: 'HSD: 30/09/22',
    rule_id: 2953345,
    saved: false,
    seller_id: 0,
    seller_name: null,
    short_description: 'Cho đơn hàng từ 200K',
    short_title: 'Hoàn 50K Xu',
    simple_action: 'cart_fixed',
    status: 'active',
    tags: ['KH mới'],
    url: '',
    web_url: null,
  },
  {
    app_url: null,
    coupon_code: 'MOCA2920',
    coupon_id: 62406984,
    coupon_type: 'MOCA_COUPON',
    discount_amount: 20000,
    expired_at: 1664557199,
    icon_name: 'Ví Moca',
    icon_url:
      'https://salt.tikicdn.com/cache/128x128/ts/upload/a8/e1/32/f231d8edf0241c00efdda571bbc0c962.jpg',
    label: 'Giảm 20K',
    long_description:
      'Giảm 20K cho đơn hàng từ 199K.\nKhông áp dụng cho các sản phẩm trong danh mục Sữa cho bé dưới 24 tháng , Phiếu quà tặng, Quảng cáo Tiki Ads, Sản phẩm dịch vụ số, Tini App, Sim số - Thẻ cào - Thẻ game, Tini App SD, Mã Phiếu Quà Tặng Tiki, Rượu từ 15%.\nKhông áp dụng cho 1 số nhà bán.\nChỉ áp dụng khi mua hàng trên Tiki Mobile App.\nMỗi khách hàng được sử dụng tối đa 1 lần.\nKhông áp dụng cho trả góp.',
    min_amount: 199000,
    out_of_stock: false,
    payment: null,
    period: 'HSD: 30/09/22',
    rule_id: 3004233,
    saved: false,
    seller_id: 0,
    seller_name: null,
    short_description: 'Cho đơn hàng từ 199K',
    short_title: 'Giảm 20K',
    simple_action: 'cart_fixed',
    status: 'active',
    tags: ['Chỉ cho App'],
    url: 'https://tiki.vn/khuyen-mai/moca-grab-tiki',
    web_url: null,
  },
  {
    app_url: null,
    coupon_code: 'HELLO88',
    coupon_id: 61246205,
    coupon_type: 'SELLER_COUPON',
    discount_amount: 5000,
    expired_at: 1669782059,
    icon_name: 'Nụ Cười',
    icon_url:
      'https://vcdn.tikicdn.com/cache/128x128/ts/seller/50/d4/ff/70d372a6f3c4b66bb5318c3a9dae606c.jpg',
    label: 'Giảm 5K',
    long_description: 'Giảm 5K cho đơn hàng từ 250K.\nÁp dụng cho sản phẩm của Nụ Cười.',
    min_amount: 250000,
    out_of_stock: false,
    payment: null,
    period: 'HSD: 30/11/22',
    rule_id: 2963790,
    saved: false,
    seller_id: 148768,
    seller_name: null,
    short_description: 'Cho đơn hàng từ 250K',
    short_title: 'Giảm 5K',
    simple_action: 'cart_fixed',
    status: 'active',
    tags: [],
    url: 'https://tiki.vn/cua-hang/nu-cuoi',
    web_url: null,
  },
];

Page({
  data: {
    coupons,
  },
  onSelect(data) {
    console.log('data :>> ', data);
  },
});
