name: Publish version

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: mac-m1
    steps:
      # we need to fetch full git in-order for lerna to
      # detect rc count
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.0

      - name: Setup npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: Install packages
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Publish
        run: yarn deploy:ci
